# Generated by Django 3.2.4 on 2021-06-04 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diploms', '0004_comment_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacansia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('salary', models.IntegerField()),
                ('address', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'vacansies',
            },
        ),
    ]
