# Generated by Django 3.2.4 on 2021-06-05 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diploms', '0007_remove_vacansia_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacansia',
            name='city',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='diploms.city'),
            preserve_default=False,
        ),
    ]
