# Generated by Django 3.2.4 on 2021-06-05 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diploms', '0013_auto_20210605_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacansia',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='diploms/img/'),
        ),
    ]
