# Generated by Django 3.2.4 on 2021-06-07 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diploms', '0021_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='origin',
            field=models.CharField(default=None, max_length=500),
            preserve_default=False,
        ),
    ]
