# Generated by Django 3.2.4 on 2021-06-07 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diploms', '0022_news_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='answer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
