# Generated by Django 3.2.4 on 2021-06-07 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diploms', '0023_message_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='answer',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='title',
            field=models.ForeignKey(default='Я ПОКУПАТЕЛЬ', on_delete=django.db.models.deletion.CASCADE, to='diploms.topic'),
        ),
    ]
