# Generated by Django 3.2.4 on 2021-06-07 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diploms', '0024_auto_20210607_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='answer',
            field=models.TextField(blank=True, default=' ', null=True),
        ),
    ]
