# Generated by Django 3.2.4 on 2021-06-07 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diploms', '0026_message_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
