# Generated by Django 3.2.4 on 2021-06-08 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diploms', '0027_alter_news_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image_origin_str',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='news',
            name='image_url',
            field=models.CharField(default='', max_length=500),
        ),
    ]
