# Generated by Django 3.2.4 on 2021-06-08 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diploms', '0028_auto_20210608_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacansia',
            name='image_origin_str',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='vacansia',
            name='image_url',
            field=models.CharField(default=' ', max_length=500),
        ),
        migrations.AlterField(
            model_name='news',
            name='image_origin_str',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='news',
            name='image_url',
            field=models.CharField(default=' ', max_length=500),
        ),
    ]
