# Generated by Django 3.2.4 on 2021-06-10 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diploms', '0029_auto_20210608_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media_cdn'),
        ),
    ]
