# Generated by Django 3.2.4 on 2021-06-10 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diploms', '0033_alter_message_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
