# Generated by Django 3.2.4 on 2021-06-10 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diploms', '0034_alter_message_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacansia',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
